// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEdmFN0KZSSxHmgT1yHCymzTQBjJu5PbE',
    appId: '1:761538757064:web:dd8571fc2c2510f918c0fd',
    messagingSenderId: '761538757064',
    projectId: 'chat-app-ae509',
    authDomain: 'chat-app-ae509.firebaseapp.com',
    storageBucket: 'chat-app-ae509.firebasestorage.app',
    measurementId: 'G-BBP1K930MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSztaIdx2yEeBgYsgV-V5mggGPbPn2aA0',
    appId: '1:761538757064:android:d3cfe717f0b1408318c0fd',
    messagingSenderId: '761538757064',
    projectId: 'chat-app-ae509',
    storageBucket: 'chat-app-ae509.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0P8h6NwxMYFkFvRcUOzGWqMSLBAFtZMQ',
    appId: '1:761538757064:ios:84ab429b9733a6b818c0fd',
    messagingSenderId: '761538757064',
    projectId: 'chat-app-ae509',
    storageBucket: 'chat-app-ae509.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0P8h6NwxMYFkFvRcUOzGWqMSLBAFtZMQ',
    appId: '1:761538757064:ios:84ab429b9733a6b818c0fd',
    messagingSenderId: '761538757064',
    projectId: 'chat-app-ae509',
    storageBucket: 'chat-app-ae509.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEdmFN0KZSSxHmgT1yHCymzTQBjJu5PbE',
    appId: '1:761538757064:web:39ec844d083c8f0a18c0fd',
    messagingSenderId: '761538757064',
    projectId: 'chat-app-ae509',
    authDomain: 'chat-app-ae509.firebaseapp.com',
    storageBucket: 'chat-app-ae509.firebasestorage.app',
    measurementId: 'G-15924VTD5K',
  );
}
